apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: analytics
    basicAuth: false
    isDefault: true
    jsonData:
      defaultDatabase: analytics
      username: default
      password: ""
    editable: true